<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>


	<main>
        <div class="container"></div>
        <form method="POST" name="login" id="login_hp">

            <div class="pseudo_container">
                <label for="title">Username</label>
                <input type="text" name="userName" id="userName" placeholder="username" value=""
            </div>

            <div class="pass_container">
                <label for="content">Password</label>
                <input type="password" name="password" id="password" placeholder="password">
            </div>

            <button type="submit" id="login_bttn" >login</button>
		</form>
	</main>


</body>
</html>