<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>


	<main>
        <div class="container input-group container-fluid input-group">
            <div class="row">
                <form method="POST" name="login" id="login_hp">

                    <div class="pseudo_container col-lg-10">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        <span class="input-group-addon" id="basic-addon1">Username</span>
                        <input type="text" name="userName" id="userName" placeholder="username" value=""
                    </div>

                    <div class="pass_container col-lg-10">
                        <span class="input-group-addon" id="basic-addon2">Password</span>
                        <input type="password" name="password" id="password" placeholder="password">
                    </div>

                    <button type="submit" class="btn btn-success" id="login_bttn" >login</button>
                </form>
            </div>
        </div>
	</main>


</body>
</html>