<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="../../public/css/bootstrap.min.css" />
    <script type="text/javascript" src="../../public/js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="../../public/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../../public/css/jean.css">
    <title>homepage</title>
</head>
<body>

	<main>
        <div class="container input-group">

                <form method="POST" name="login" id="login_hp">


                        <div class="row">
                            <div class="col-lg-3 input-group">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                             </div>
                        </div>
                        <div class="row">
                            <div class="input-group col-lg-4">
                            <span class="input-group-addon" id="basic-addon1">Username</span>
                            <input type="text" name="userName" id="userName" class="form-control" placeholder="username" aria-describedby="basic-addon1" value="">
                            </div>
                        </div>
                    <div class="row">
                        <div class="input-group col-lg-4">
                            <span class="input-group-addon" id="basic-addon2">Password</span>
                            <input type="password" name="password" id="password" class="form-control" placeholder="password" aria-describedby="basic-addon2">
                         </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-3">
                           <button type="submit" class="btn btn-success" id="login_bttn" >login</button>
                        </div>
                    </div>
                </form>
        </div>
	</main>


</body>
</html>