<div class="profilPublicEditable">
	<h1>Profil</h1>
	<h2>Pseudo : <?php htmlentities($infos['nick']) ?></h2>
	<h2>Nom : <?php htmlentities($infos['firstname']) ?> Prénom : <?php htmlentities($infos['lastname']) ?> </h2>
	<h2>Mot de passe : <?php htmlentities($infos['password']) ?></h2>
	<h2>Mail : <?php htmlentities($infos['mail']) ?></h2>
	<!-- <h2>amis</h2> -->
	<h2>Skill : <?php htmlentities($infos['skill']) ?></h2>
	<h2>Biographie : <?php htmlentities($infos['bio']) ?></h2>
	<h2>Entreprises : <?php htmlentities($infos['entreprise']) ?></h2>
</div>