<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="icon" type="image/png" href="public/img/logo.png" />
	<title>devNetWork</title>
	<link href="public/css/style.css" rel="stylesheet">
	<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
</head>
<body>
	<?php require('app/header.php');?>
	<?php require('app/content.php');?>
	<?php require('app/footer.php');?>
	<script	src="https://code.jquery.com/jquery-3.2.1.min.js"
	integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
	crossorigin="anonymous"></script>
	<script src="public/js/user.js"></script>
	<script src="public/js/main.js"></script>
</body>
</html>
