<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="../../public/css/bootstrap.min.css" />
    <script type="text/javascript" src="../../public/js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="../../public/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../../public/css/jean.css">
    <title>registration</title>
</head>
<body>



<main>

    <div class="container">

            <form method="POST">


                <div class="row">
                    <div class="pass_container col-lg-3">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                     </div>
                </div>
                <div class="row">
                    <div class="input-group col-lg-4">
                    <span class="input-group-addon" id="basic-addon1">Username</span>
                    <input type="text" name="userName" class="form-control" id="userName" placeholder="username" aria-describedby="basic-addon1" value="">
                    </div>
                    <div class="input-group col-lg-4">
                        <span class="input-group-addon" id="basic-addon2">Password</span>
                        <input type="password" name="password" class="form-control" id="password" placeholder="password" aria-describedby="basic-addon2">
                    </div>

                    <div class="input-group col-lg-4">
                        <span class="input-group-addon" id="basic-addon3">Password Re-check</span>
                        <input type="password" name="password_2check" class="form-control" id="password_2check" placeholder="password re-check" aria-describedby="basic-addon3">
                    </div>
                    <div class="email_container col-lg-4 input-group">
                        <span class="input-group-addon" id="basic-addon4">E-mail</span>
                        <input type="email" id="email" class="form-control" placeholder="E-mail" aria-describedby="basic-addon4">
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3">
                        <button type="submit" class="btn btn-success" id="register_bttn" >Register</button>
                    </div>
                </div>
        </form>
    </div>
</main>


</body>
</html>