<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>



<main>
    <div class="container"></div>
    <form method="POST">

        <div class="pseudo_container">
            <label for="title">Username</label>
            <input type="text" name="userName" id="userName" placeholder="username" value=""
            <input type="text" name="userName" id="userName" placeholder="username" value=""
        </div>
        <div class="pass_container">
            <label for="content">password</label>
            <input type="password" name="password" id="password" placeholder="password">
        </div>

        <div class="pass2_container">
            <label for="content">password recheck</label>
            <input type="password" name="password_2check" id="password_2check" placeholder="password check">
        </div>
        <div>
            <label for="title">E-mail</label>
            <input type="email" id="email" placeholder="E-mail">
        </div>

        <button type="submit" id="register_bttn" >Register</button>
    </form>
</main>


</body>
</html>